name: Release Helm Chart

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    uses: Jmainguy/helm-workflows/.github/workflows/helm-release.yml@v1.3
    with:
      chart_name: helm-webapp
      chart_path: .
      helm_registry: zot.soh.re
      registry_namespace: jmainguy
      notation_key_name: jon-soh-re
    secrets:
      release_token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
      helm_username: ${{ secrets.HELM_USERNAME }}
      helm_password: ${{ secrets.HELM_PASSWORD }}
      notation_private_key: ${{ secrets.NOTATION_PRIVATE_KEY }}
      notation_certificate_chain: ${{ secrets.NOTATION_CERTIFICATE_CHAIN }}
      notation_ca_certificate: ${{ secrets.NOTATION_CA_CERTIFICATE }}
